# generated by datamodel-codegen:
#   filename:  create.json
#   timestamp: 2026-02-09T16:54:02+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class CreateUser(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    authentication_provider_id: Annotated[str, Field(alias='authenticationProviderId')]
    """
    Authentication provider identifier
    """
    persistent_user_id: Annotated[str, Field(alias='persistentUserId')]
    """
    Persistent identifier for the user
    """
    identifier: str
    """
    User identifier (username)
    """
    first_name: Annotated[str, Field(alias='firstName')]
    """
    First name of the user
    """
    last_name: Annotated[str, Field(alias='lastName')]
    """
    Last name of the user
    """
    email: EmailStr
    """
    Email address of the user
    """
