# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2026-02-09T16:54:01+00:00
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class User(BaseModel):
    """
    Schema for a Dataverse user object
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: int
    """
    Unique identifier for the user
    """
    identifier: str
    """
    User identifier (username)
    """
    display_name: Annotated[str, Field(alias='displayName')]
    """
    Display name of the user
    """
    first_name: Annotated[str, Field(alias='firstName')]
    """
    First name of the user
    """
    last_name: Annotated[str, Field(alias='lastName')]
    """
    Last name of the user
    """
    email: EmailStr
    """
    Email address of the user
    """
    superuser: bool
    """
    Whether the user has superuser privileges
    """
    deactivated: bool
    """
    Whether the user account is deactivated
    """
    affiliation: Optional[str] = None
    """
    User's institutional affiliation
    """
    position: Optional[str] = None
    """
    User's position or title
    """
    persistent_user_id: Annotated[str, Field(alias='persistentUserId')]
    """
    Persistent identifier for the user
    """
    created_time: Annotated[datetime, Field(alias='createdTime')]
    """
    Timestamp when the user account was created
    """
    last_login_time: Annotated[Optional[datetime], Field(alias='lastLoginTime')] = None
    """
    Timestamp of the user's last login
    """
    last_api_use_time: Annotated[Optional[datetime], Field(alias='lastApiUseTime')] = (
        None
    )
    """
    Timestamp of the user's last API usage
    """
    authentication_provider_id: Annotated[str, Field(alias='authenticationProviderId')]
    """
    ID of the authentication provider used by the user
    """
