# generated by datamodel-codegen:
#   filename:  metadatablock.json
#   timestamp: 2026-02-09T16:54:02+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Dict, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class MetadataField(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    display_name: Annotated[str, Field(alias='displayName')]
    display_on_create: Annotated[Optional[bool], Field(alias='displayOnCreate')] = None
    title: str
    type: Literal[
        'TEXT', 'TEXTBOX', 'STRING', 'DATE', 'EMAIL', 'URL', 'FLOAT', 'INT', 'NONE'
    ]
    type_class: Annotated[
        Literal['primitive', 'compound', 'controlledVocabulary'],
        Field(alias='typeClass'),
    ]
    watermark: Optional[str] = None
    description: Optional[str] = None
    multiple: bool
    is_controlled_vocabulary: Annotated[bool, Field(alias='isControlledVocabulary')]
    display_format: Annotated[str, Field(alias='displayFormat')]
    display_order: Annotated[int, Field(alias='displayOrder')]
    is_required: Annotated[bool, Field(alias='isRequired')]
    child_fields: Annotated[
        Optional[Dict[str, MetadataField]], Field(alias='childFields')
    ] = None
    controlled_vocabulary_values: Annotated[
        Optional[List[str]], Field(alias='controlledVocabularyValues')
    ] = None


class MetadatablockSpecification(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    name: str
    display_name: Annotated[str, Field(alias='displayName')]
    display_on_create: Annotated[Optional[bool], Field(alias='displayOnCreate')] = None
    fields: Dict[str, MetadataField]


MetadataField.model_rebuild()
