# generated by datamodel-codegen:
#   filename:  overview.json
#   timestamp: 2026-02-09T16:54:02+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class MetadatablockMeta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    name: str
    display_name: Annotated[str, Field(alias='displayName')]
    display_on_create: Annotated[Optional[bool], Field(alias='displayOnCreate')] = None


class MetadatablocksOverviewResponse(RootModel[List[Any]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Annotated[List[Any], Field(title='MetadatablocksOverviewResponse')]
