# generated by datamodel-codegen:
#   filename:  hub.json
#   timestamp: 2026-02-09T16:54:04+00:00
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Hub(RootModel[Any]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Annotated[Any, Field(title='Hub')]


class Installation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    dv_hub_id: Annotated[Optional[str], Field(alias='dvHubId')] = None
    name: Optional[str] = None
    description: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    hostname: Optional[str] = None
    country: Optional[str] = None
    continent: Optional[str] = None
    launch_year: Annotated[Optional[int], Field(alias='launchYear')] = None
    gdcc_member: Annotated[Optional[bool], Field(alias='gdccMember')] = None
    doi_authority: Annotated[Optional[str], Field(alias='doiAuthority')] = None
    contact_email: Annotated[Optional[str], Field(alias='contactEmail')] = None
    is_active: Annotated[Optional[bool], Field(alias='isActive')] = None


class InstallationStatus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    record_id: Annotated[Optional[int], Field(alias='recordId')] = None
    installation: Optional[Installation] = None
    status: Optional[str] = None
    version: Optional[str] = None
    build: Optional[str] = None
    record_date: Annotated[Optional[datetime], Field(alias='recordDate')] = None


class InstallationStatusResponse(RootModel[List[InstallationStatus]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[InstallationStatus]
