# generated by datamodel-codegen:
#   filename:  metrics.json
#   timestamp: 2026-02-09T16:53:54+00:00
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class MetricsResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    count: int
