# generated by datamodel-codegen:
#   filename:  search.json
#   timestamp: 2026-02-09T16:53:58+00:00
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Dict, List, Literal, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Contact(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    affiliation: Optional[str] = None


class Snippet1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    snippets: Optional[List[str]] = None


class FacetLabel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    friendly: Optional[str] = None
    labels: Optional[List[Dict[str, int]]] = None


class Match(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[Union[str, Snippet1]] = None
    name: Optional[Union[str, Snippet1]] = None
    author_name: Annotated[
        Optional[Union[str, Snippet1]], Field(alias='authorName')
    ] = None
    ds_description_value: Annotated[
        Optional[Union[str, Snippet1]], Field(alias='dsDescriptionValue')
    ] = None
    title: Optional[Union[str, Snippet1]] = None


class Facet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    subject_ss: Optional[FacetLabel] = None
    author_name_ss: Annotated[Optional[FacetLabel], Field(alias='authorName_ss')] = None
    publication_date: Annotated[
        Optional[FacetLabel], Field(alias='publicationDate')
    ] = None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    q: Optional[str] = None
    total_count: int
    start: Optional[int] = None
    spelling_alternatives: Optional[Dict[str, List[str]]] = None
    items: List[Item]
    count_in_response: Optional[int] = None
    facets: Optional[List[Facet]] = None


class Item(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    type: Optional[str] = None
    url: Optional[AnyUrl] = None
    image_url: Optional[AnyUrl] = None
    identifier: Optional[str] = None
    description: Optional[str] = None
    published_at: Optional[datetime] = None
    publication_statuses: Annotated[
        Optional[List[str]], Field(alias='publicationStatuses')
    ] = None
    affiliation: Optional[str] = None
    parent_dataverse_name: Annotated[
        Optional[str], Field(alias='parentDataverseName')
    ] = None
    parent_dataverse_identifier: Annotated[
        Optional[str], Field(alias='parentDataverseIdentifier')
    ] = None
    file_id: Optional[str] = None
    file_type: Optional[str] = None
    file_content_type: Optional[str] = None
    size_in_bytes: Optional[int] = None
    md5: Optional[str] = None
    file_persistent_id: Optional[str] = None
    dataset_name: Optional[str] = None
    dataset_id: Optional[str] = None
    dataset_persistent_id: Optional[str] = None
    dataset_citation: Optional[str] = None
    release_or_create_date: Annotated[
        Optional[datetime], Field(alias='releaseOrCreateDate')
    ] = None
    global_id: Optional[str] = None
    publisher: Optional[str] = None
    citation_html: Annotated[Optional[str], Field(alias='citationHtml')] = None
    identifier_of_dataverse: Optional[str] = None
    name_of_dataverse: Optional[str] = None
    citation: Optional[str] = None
    storage_identifier: Annotated[Optional[str], Field(alias='storageIdentifier')] = (
        None
    )
    subjects: Optional[List[str]] = None
    file_count: Annotated[Optional[int], Field(alias='fileCount')] = None
    version_id: Annotated[Optional[int], Field(alias='versionId')] = None
    version_state: Annotated[Optional[str], Field(alias='versionState')] = None
    major_version: Annotated[Optional[int], Field(alias='majorVersion')] = None
    minor_version: Annotated[Optional[int], Field(alias='minorVersion')] = None
    created_at: Annotated[Optional[datetime], Field(alias='createdAt')] = None
    updated_at: Annotated[Optional[datetime], Field(alias='updatedAt')] = None
    contacts: Optional[List[Contact]] = None
    matches: Optional[List[Match]] = None
    score: Optional[float] = None
    authors: Optional[List[str]] = None
    producers: Optional[List[str]] = None
    metadata_blocks: Annotated[
        Optional[Dict[str, MetadataBlock]], Field(alias='metadataBlocks')
    ] = None


class MetadataBlock(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    display_name: Annotated[Optional[str], Field(alias='displayName')] = None
    name: Optional[str] = None
    fields: Optional[List[FieldModel]] = None


class FieldModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type_name: Annotated[Optional[str], Field(alias='typeName')] = None
    multiple: Optional[bool] = None
    type_class: Annotated[
        Optional[Literal['primitive', 'compound', 'controlledVocabulary']],
        Field(alias='typeClass'),
    ] = None
    value: Optional[
        Union[
            str,
            float,
            bool,
            List[Union[str, float, bool, Dict[str, FieldModel]]],
            Dict[str, FieldModel],
        ]
    ] = None


SearchResponse.model_rebuild()
Item.model_rebuild()
MetadataBlock.model_rebuild()
FieldModel.model_rebuild()
