# generated by datamodel-codegen:
#   filename:  exporters.json
#   timestamp: 2026-02-09T16:54:03+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Exporter(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    display_name: Annotated[str, Field(alias='displayName')]
    media_type: Annotated[str, Field(alias='mediaType')]
    is_harvestable: Annotated[bool, Field(alias='isHarvestable')]
    is_visible_in_user_interface: Annotated[
        bool, Field(alias='isVisibleInUserInterface')
    ]
    xml_name_space: Annotated[Optional[str], Field(alias='XMLNameSpace')] = None
    xml_schema_location: Annotated[Optional[str], Field(alias='XMLSchemaLocation')] = (
        None
    )
    xml_schema_version: Annotated[Optional[str], Field(alias='XMLSchemaVersion')] = None


class ExportersResponse(RootModel[Optional[Dict[str, Exporter]]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Optional[Dict[str, Exporter]] = None
