# generated by datamodel-codegen:
#   filename:  licenses.json
#   timestamp: 2026-02-09T16:54:03+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class License(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    name: str
    short_description: Annotated[str, Field(alias='shortDescription')]
    uri: str
    icon_url: Annotated[Optional[str], Field(alias='iconUrl')] = None
    active: bool
    is_default: Annotated[bool, Field(alias='isDefault')]
    sort_order: Annotated[int, Field(alias='sortOrder')]
    rights_identifier: Annotated[Optional[str], Field(alias='rightsIdentifier')] = None
    rights_identifier_scheme: Annotated[
        Optional[str], Field(alias='rightsIdentifierScheme')
    ] = None
    scheme_uri: Annotated[Optional[str], Field(alias='schemeUri')] = None
    language_code: Annotated[Optional[str], Field(alias='languageCode')] = None
