# generated by datamodel-codegen:
#   filename:  terms_of_use.json
#   timestamp: 2026-02-09T16:54:02+00:00
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TermsOfUseResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: str
