# generated by datamodel-codegen:
#   filename:  version.json
#   timestamp: 2026-02-09T16:54:03+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class VersionResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    version: str
    build: Optional[str] = None
