# generated by datamodel-codegen:
#   filename:  access.json
#   timestamp: 2026-02-09T16:53:57+00:00
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Annotated, List

from pydantic import BaseModel, ConfigDict, EmailStr, Field, RootModel


class AccessRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    """
    Unique identifier for the access request
    """
    identifier: str
    """
    User identifier
    """
    display_name: Annotated[str, Field(alias='displayName')]
    """
    Display name of the user
    """
    first_name: Annotated[str, Field(alias='firstName')]
    """
    First name of the user
    """
    last_name: Annotated[str, Field(alias='lastName')]
    """
    Last name of the user
    """
    email: EmailStr
    """
    Email address of the user
    """
    superuser: bool
    """
    Whether the user is a superuser
    """
    deactivated: bool
    """
    Whether the user account is deactivated
    """
    persistent_user_id: Annotated[str, Field(alias='persistentUserId')]
    """
    Persistent user identifier
    """
    created_time: Annotated[datetime, Field(alias='createdTime')]
    """
    Timestamp when the user was created
    """
    last_login_time: Annotated[datetime, Field(alias='lastLoginTime')]
    """
    Timestamp of the user's last login
    """
    last_api_use_time: Annotated[datetime, Field(alias='lastApiUseTime')]
    """
    Timestamp of the user's last API usage
    """
    authentication_provider_id: Annotated[str, Field(alias='authenticationProviderId')]
    """
    Authentication provider identifier
    """


class AccessRequests(RootModel[List[AccessRequest]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Annotated[List[AccessRequest], Field(title='AccessRequests')]
