# generated by datamodel-codegen:
#   filename:  filemeta.json
#   timestamp: 2026-02-09T16:53:57+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator


class Model(BaseModel):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Checksum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[str] = None
    value: Optional[str] = None


class DataFile(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[int] = None
    persistent_id: Annotated[Optional[str], Field(alias='persistentId')] = None
    filename: Optional[str] = None
    content_type: Annotated[Optional[str], Field(alias='contentType')] = None
    friendly_type: Annotated[Optional[str], Field(alias='friendlyType')] = None
    filesize: Optional[int] = None
    description: Optional[str] = None
    categories: Optional[List[str]] = None
    storage_identifier: Annotated[Optional[str], Field(alias='storageIdentifier')] = (
        None
    )
    directory_label: Annotated[Optional[str], Field(alias='directoryLabel')] = None
    root_data_file_id: Annotated[Optional[int], Field(alias='rootDataFileId')] = None
    md5: Optional[str] = None
    checksum: Optional[Checksum] = None
    tabular_data: Annotated[Optional[bool], Field(alias='tabularData')] = None
    creation_date: Annotated[Optional[str], Field(alias='creationDate')] = None
    file_access_request: Annotated[Optional[bool], Field(alias='fileAccessRequest')] = (
        None
    )


class FileInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[int] = None
    persistent_id: Annotated[Optional[str], Field(alias='persistentId')] = None
    description: Optional[str] = None
    label: Optional[str] = None
    restricted: Optional[bool] = None
    directory_label: Annotated[Optional[str], Field(alias='directoryLabel')] = None
    version: Optional[int] = None
    dataset_version_id: Annotated[Optional[int], Field(alias='datasetVersionId')] = None
    categories: Optional[List[str]] = None
    data_file: Annotated[Optional[DataFile], Field(alias='dataFile')] = None

    @model_validator(mode='after')
    def _backfill_categories(self) -> 'FileInfo':
        # Some Dataverse endpoints return a file's categories on the nested
        # ``dataFile`` rather than at the file-metadata level. Surface them at
        # the top level when the file-metadata categories are absent so callers
        # have a single, reliable place to read them.
        if not self.categories and self.data_file and self.data_file.categories:
            self.categories = self.data_file.categories
        return self


class UploadBody(DataFile):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    force_replace: Annotated[Optional[bool], Field(alias='forceReplace')] = None
    tab_ingest: Annotated[Optional[bool], Field(alias='tabIngest')] = None
    restrict: Optional[bool] = None


class UploadResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    files: Optional[List[FileInfo]] = None
