# generated by datamodel-codegen:
#   filename:  redetect.json
#   timestamp: 2026-02-09T16:53:57+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class RedetectedFileType(BaseModel):
    """
    Schema for the response from the file redetect API endpoint
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    dry_run: Annotated[bool, Field(alias='dryRun')]
    """
    Whether this was a dry run operation
    """
    old_content_type: Annotated[str, Field(alias='oldContentType')]
    """
    The previous content type of the file
    """
    new_content_type: Annotated[str, Field(alias='newContentType')]
    """
    The new detected content type of the file
    """
