# generated by datamodel-codegen:
#   filename:  restrict.json
#   timestamp: 2026-02-09T16:53:58+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class RestrictFileBody(BaseModel):
    """
    Restrict or unrestrict a datafile.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    restrict: bool
    """
    Whether to restrict access to the file
    """
    enable_access_request: Annotated[
        Optional[bool], Field(alias='enableAccessRequest')
    ] = None
    """
    Whether to enable access requests for the restricted file
    """
    terms_of_access: Annotated[Optional[str], Field(alias='termsOfAccess')] = None
    """
    Reason or terms for the restricted access
    """
