# generated by datamodel-codegen:
#   filename:  update.json
#   timestamp: 2026-02-09T16:53:58+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class UpdateBody(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    prov_freeform: Annotated[Optional[str], Field(alias='provFreeform')] = None
    categories: Optional[List[str]] = None
    data_file_tags: Annotated[Optional[List[str]], Field(alias='dataFileTags')] = None
    restrict: Optional[bool] = None
