# generated by datamodel-codegen:
#   filename:  assignee.json
#   timestamp: 2026-02-09T16:53:55+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Role(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    alias: str
    name: str
    description: str
    id: Optional[int] = None
    permissions: List[str]
    owner_id: Annotated[Optional[int], Field(alias='ownerId')] = None


class Assignee(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    assignee: str
    role_id: Annotated[int, Field(alias='roleId')]
    definition_point_id: Annotated[int, Field(alias='definitionPointId')]
    role: Optional[Role] = None
