# generated by datamodel-codegen:
#   filename:  collection.json
#   timestamp: 2026-02-09T16:53:56+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class Collection(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    alias: str
    name: str
    affiliation: Optional[str] = None
    permission_root: Annotated[Optional[bool], Field(alias='permissionRoot')] = None
    description: Optional[str] = None
    dataverse_type: Annotated[Optional[str], Field(alias='dataverseType')] = None
    is_metadata_block_root: Annotated[
        Optional[bool], Field(alias='isMetadataBlockRoot')
    ] = None
    is_facet_root: Annotated[Optional[bool], Field(alias='isFacetRoot')] = None
    owner_id: Annotated[Optional[int], Field(alias='ownerId')] = None
    creation_date: Annotated[Optional[str], Field(alias='creationDate')] = None
    effective_requires_files_to_publish_dataset: Annotated[
        Optional[bool], Field(alias='effectiveRequiresFilesToPublishDataset')
    ] = None
    is_released: Annotated[Optional[bool], Field(alias='isReleased')] = None
