# generated by datamodel-codegen:
#   filename:  content.json
#   timestamp: 2026-02-09T16:53:54+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Collection(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    title: str
    type: str


class Dataset(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[int] = None
    identifier: str
    persistent_url: Annotated[str, Field(alias='persistentUrl')]
    protocol: str
    authority: str
    separator: str
    publisher: str
    publication_date: Annotated[Optional[str], Field(alias='publicationDate')] = None
    storage_identifier: Annotated[str, Field(alias='storageIdentifier')]
    type: str


class CollectionContent(RootModel[List[Union[Collection, Dataset]]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Annotated[List[Union[Collection, Dataset]], Field(title='CollectionContent')]
