# generated by datamodel-codegen:
#   filename:  create.json
#   timestamp: 2026-02-09T16:53:55+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class Create(BaseModel):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Contact(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    contact_email: Annotated[str, Field(alias='contactEmail')]
    display_order: Annotated[Optional[int], Field(alias='displayOrder')] = None


class CollectionCreateBody(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    alias: str
    description: str
    affiliation: str
    dataverse_type: Annotated[
        Literal[
            'DEPARTMENT',
            'JOURNALS',
            'LABORATORY',
            'ORGANIZATIONS_INSTITUTIONS',
            'RESEARCHERS',
            'RESEARCH_GROUP',
            'RESEARCH_PROJECTS',
            'TEACHING_COURSES',
            'UNCATEGORIZED',
        ],
        Field(alias='dataverseType'),
    ]
    dataverse_contacts: Annotated[List[Contact], Field(alias='dataverseContacts')]


class CollectionCreateResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    alias: str
    name: str
    affiliation: Optional[str] = None
    dataverse_contacts: Annotated[
        Optional[List[Contact]], Field(alias='dataverseContacts')
    ] = None
    permission_root: Annotated[Optional[bool], Field(alias='permissionRoot')] = None
    description: Optional[str] = None
    dataverse_type: Annotated[
        Optional[
            Literal[
                'DEPARTMENT',
                'JOURNALS',
                'LABORATORY',
                'ORGANIZATIONS_INSTITUTIONS',
                'RESEARCHERS',
                'RESEARCH_GROUP',
                'RESEARCH_PROJECTS',
                'TEACHING_COURSES',
                'UNCATEGORIZED',
            ]
        ],
        Field(alias='dataverseType'),
    ] = None
    is_metadata_block_root: Annotated[
        Optional[bool], Field(alias='isMetadataBlockRoot')
    ] = None
    is_facet_root: Annotated[Optional[bool], Field(alias='isFacetRoot')] = None
    owner_id: Annotated[Optional[int], Field(alias='ownerId')] = None
    creation_date: Annotated[Optional[str], Field(alias='creationDate')] = None
    effective_requires_files_to_publish_dataset: Annotated[
        Optional[bool], Field(alias='effectiveRequiresFilesToPublishDataset')
    ] = None
    is_released: Annotated[Optional[bool], Field(alias='isReleased')] = None
