# generated by datamodel-codegen:
#   filename:  delete.json
#   timestamp: 2026-02-09T16:53:55+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class CollectionDeleteResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: Optional[str] = None
