# generated by datamodel-codegen:
#   filename:  update.json
#   timestamp: 2026-02-09T16:53:56+00:00
#   version:   0.28.5

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class DataverseContact(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    contact_email: Annotated[EmailStr, Field(alias='contactEmail')]


class UpdateCollection(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    alias: Optional[str] = None
    dataverse_contacts: Annotated[
        Optional[List[DataverseContact]], Field(alias='dataverseContacts')
    ] = None
    affiliation: Annotated[
        Optional[str], Field(examples=['Scientific Research University'])
    ] = None
    description: Optional[str] = None
    dataverse_type: Annotated[Optional[str], Field(alias='dataverseType')] = None
