name: Unit tests
on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Test pyDataverse
    env:
      PORT: 8080
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: Run Dataverse Action
        id: dataverse
        uses: gdcc/dataverse-action@main
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry

          poetry install --with tests

      - name: Run tests
        env:
          API_TOKEN_SUPERUSER: ${{ steps.dataverse.outputs.api_token }}
          API_TOKEN: ${{ steps.dataverse.outputs.api_token }}
          BASE_URL: ${{ steps.dataverse.outputs.base_url }}
          DV_VERSION: ${{ steps.dataverse.outputs.dv_version }}
        run: |
          python3 -m poetry run pytest
