name: Unit tests
on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    name: Test pyDataverse
    env:
      PORT: 8080
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Dataverse Action
        id: dataverse
        uses: gdcc/dataverse-action@main

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python Dependencies
        run: |
          uv pip install --system ".[tests,mcp]"

      - name: Run tests
        env:
          API_TOKEN_SUPERUSER: ${{ steps.dataverse.outputs.api_token }}
          API_TOKEN: ${{ steps.dataverse.outputs.api_token }}
          BASE_URL: ${{ steps.dataverse.outputs.base_url }}
          DV_VERSION: ${{ steps.dataverse.outputs.dv_version }}
        run: |
          pytest -vv
